---
# MAIN FILE TO RUN EACH TASK IN ORDER NEEDED
#GATHERS CDP INFORMATION AND SAVES TO YAML FILE
- name: "Create CDP NEIGHBOR INFORMATION"
  ansible.builtin.include_tasks: "cdp_info.yml"

#GATHERS INTERFACE INFORMATION FROM HOST OF EACH NEIGHBOR CONNECTED
- name: "GATHER RUNNING INTERFACE CONFIGURATIONS FROM HOST"
  ansible.builtin.include_tasks: "intf_configs.yml"

#PUSHES INTERFACE DESCRIPTIONS TO HOST
- name: "UPDATE INTERFACE DESCRIPTIONS BASED ON CDP NEIGHBOR NAMES"
  ansible.builtin.include_tasks: "update_intf_desc.yml"